# Generated by Django 5.2.5 on 2025-08-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'タスク', 'verbose_name_plural': 'タスク一覧'},
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='親タスク'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='完了時に記録するコメント（任意）'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='タスク作成日時'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='タスク詳細'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='タスクをアーカイブする'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='タスクの完了状態'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タスク名'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日時'),
        ),
    ]
